### ISSUE TITLE
PageAttributes from Spring? 

### ISSUE THREAD

**Issue by PrzemyslawBrambor** [orange451/JRest#2]
Hello,
I just founded one mistake about:
`server.addEndpoint(HttpMethod.GET, "/", PageAttributes.MediaType.TEXT_HTML, (request)->`

Do we have there PageAttirubtes.MediaType.Text from Spring framework?

https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/MediaType.html

**Comment by orange451** [comment]
I’m not sure I fully understand your question? You must pass a MediaType value from JREST not Spring. This library doesn’t work with Spring, it is it’s own independent library.

Furthermore, JREST MediaType has an html content type, why can’t you use that?
